"""
LangGraph State Schema for Pulse IDE.

Defines the shared state structure used across all agent nodes in the
multi-agent workflow. This state is passed through the LangGraph execution
and updated by each node.
"""

from typing import TypedDict, List, Any, Literal


class AgentState(TypedDict):
    """
    Shared state structure for the Pulse IDE agent workflow.

    This TypedDict defines all state fields that are passed through
    the LangGraph execution. Each agent node reads from and writes to
    this state.

    Attributes:
        messages: Chat history and agent responses (LangChain Message objects).
        user_request: The current user instruction or question.
        mode: Interaction mode ("ask", "plan", or "agent").
        plan: List of actionable steps generated by the Planner Agent.
        file_context: Selected file content or RAG-retrieved snippets.
        feedback: User feedback for revisions or customization.
        files_modified: List of file paths that have been modified.
        code_changes: Description of code changes made by the Coder Agent.
        test_results: Validation results from the Tester Agent.
        workspace_path: Path to the current workspace directory.
    """

    # Chat and messaging
    messages: List[Any]  # List of LangChain Message objects (HumanMessage, AIMessage, etc.)

    # User input
    user_request: str  # Current user instruction or question

    # Workflow control
    mode: Literal["ask", "plan", "agent"]  # Interaction mode

    # Planning
    plan: List[str]  # Ordered list of implementation steps

    # Context and feedback
    file_context: str  # File content or RAG snippets
    feedback: str  # User feedback for revisions

    # Execution results
    files_modified: List[str]  # Paths of modified files
    files_touched: List[str]  # Tracks which files were modified for Tester validation
    code_changes: str  # Description of code modifications
    test_results: dict  # Validation results

    # Workspace
    workspace_path: str  # Path to the workspace directory


# Type alias for mode enum
Mode = Literal["ask", "plan", "agent"]


# Helper function to create initial state
def create_initial_state(
    user_request: str,
    mode: Mode = "agent",
    workspace_path: str = ""
) -> AgentState:
    """
    Create an initial AgentState with default values.

    Args:
        user_request: The user's request or question.
        mode: Interaction mode (defaults to "agent").
        workspace_path: Path to the workspace directory.

    Returns:
        AgentState: Initial state with default values.
    """
    return AgentState(
        messages=[],
        user_request=user_request,
        mode=mode,
        plan=[],
        file_context="",
        feedback="",
        files_modified=[],
        files_touched=[],
        code_changes="",
        test_results={},
        workspace_path=workspace_path
    )
